SET search_path TO order_mgmt, public;

INSERT INTO order_statuses (
    status_code,
    status_name,
    status_group,
    sort_no,
    is_terminal,
    is_active,
    description,
    created_at,
    updated_at
)
VALUES
    ('SPF-0101', 'Đang tạo đơn NVC',                 'CREATION',             1,  false, true, 'Đang gửi hoặc chờ kết quả tạo đơn từ nhà vận chuyển.', now(), now()),
    ('SPF-0102', 'Tạo đơn NVC lỗi',                 'CREATION',             2,  false, true, 'Tạo đơn nhà vận chuyển không thành công và có thể cần xử lý lại.', now(), now()),
    ('SPF-0201', 'Đã hủy',                          'CANCELLATION',         3,  true,  true, 'Đơn hàng đã được hủy thành công.', now(), now()),
    ('SPF-0202', 'Hủy đơn NVC lỗi',                 'CANCELLATION',         4,  false, true, 'Yêu cầu hủy tại nhà vận chuyển không thành công hoặc cần tra soát.', now(), now()),
    ('SPF-0301', 'Chờ lấy hàng',                    'PICKUP_WAITING',       5,  false, true, 'Đơn hàng đã sẵn sàng và đang chờ được lấy.', now(), now()),
    ('SPF-0401', 'Đang lấy hàng',                   'PICKUP',               6,  false, true, 'Nhà vận chuyển đang thực hiện lấy hàng.', now(), now()),
    ('SPF-0402', 'Lấy hàng thất bại',               'PICKUP',               7,  false, true, 'Lần lấy hàng không thành công.', now(), now()),
    ('SPF-0403', 'Đang yêu cầu lấy lại',            'PICKUP',               8,  false, true, 'Đang xử lý yêu cầu lấy lại hàng.', now(), now()),
    ('SPF-0501', 'Đã lấy hàng',                     'PICKUP_COMPLETED',      9,  false, true, 'Hàng đã được lấy khỏi điểm gửi.', now(), now()),
    ('SPF-0502', 'Đã nhập kho/bưu cục lấy',         'PICKUP_COMPLETED',      10, false, true, 'Hàng đã được nhập tại kho hoặc bưu cục lấy.', now(), now()),
    ('SPF-0601', 'Chờ bàn giao',                    'HANDOVER',              11, false, true, 'Hàng đang chờ bàn giao sang chặng hoặc nhà vận chuyển tiếp theo.', now(), now()),
    ('SPF-0602', 'NVC giao đang nhận hàng',         'HANDOVER',              12, false, true, 'Nhà vận chuyển giao đang thực hiện nhận bàn giao.', now(), now()),
    ('SPF-0603', 'Bàn giao thất bại',               'HANDOVER',              13, false, true, 'Lần bàn giao hàng không thành công.', now(), now()),
    ('SPF-0604', 'Đang yêu cầu bàn giao lại',       'HANDOVER',              14, false, true, 'Đang xử lý yêu cầu bàn giao lại.', now(), now()),
    ('SPF-0605', 'NVC giao đã nhận hàng',           'HANDOVER',              15, false, true, 'Nhà vận chuyển giao đã nhận bàn giao hàng.', now(), now()),
    ('SPF-0606', 'Đã nhập kho NVC giao',            'HANDOVER',              16, false, true, 'Hàng đã được nhập kho của nhà vận chuyển giao.', now(), now()),
    ('SPF-0701', 'Đang trung chuyển',                'TRANSIT',               17, false, true, 'Hàng đang được trung chuyển giữa các điểm khai thác.', now(), now()),
    ('SPF-0702', 'Đã đến kho/bưu cục giao',         'TRANSIT',               18, false, true, 'Hàng đã đến kho hoặc bưu cục phục vụ giao hàng.', now(), now()),
    ('SPF-0801', 'Đang giao hàng',                  'DELIVERY',              19, false, true, 'Nhà vận chuyển đang giao hàng tới người nhận.', now(), now()),
    ('SPF-0802', 'Giao hàng thất bại',              'DELIVERY',              20, false, true, 'Lần giao hàng không thành công.', now(), now()),
    ('SPF-0803', 'Đang yêu cầu giao lại',           'DELIVERY',              21, false, true, 'Đang xử lý yêu cầu giao lại hàng.', now(), now()),
    ('SPF-0901', 'Đã giao hàng',                    'DELIVERY_COMPLETED',    22, true,  true, 'Hàng đã được giao đầy đủ thành công.', now(), now()),
    ('SPF-0902', 'Đã giao một phần',                'DELIVERY_COMPLETED',    23, false, true, 'Một phần hàng đã được giao; phần còn lại tiếp tục được xử lý.', now(), now()),
    ('SPF-1001', 'Chờ xác nhận chuyển hoàn',        'RETURN',                24, false, true, 'Đang chờ xác nhận yêu cầu chuyển hoàn.', now(), now()),
    ('SPF-1002', 'Đã xác nhận chuyển hoàn',         'RETURN',                25, false, true, 'Yêu cầu chuyển hoàn đã được xác nhận.', now(), now()),
    ('SPF-1003', 'Chờ lấy hàng hoàn',               'RETURN',                26, false, true, 'Đang chờ lấy hàng để thực hiện chiều hoàn.', now(), now()),
    ('SPF-1004', 'Đang lấy hàng hoàn',              'RETURN',                27, false, true, 'Nhà vận chuyển đang lấy hàng cho chiều hoàn.', now(), now()),
    ('SPF-1005', 'Lấy hàng hoàn thất bại',          'RETURN',                28, false, true, 'Lần lấy hàng hoàn không thành công.', now(), now()),
    ('SPF-1006', 'Đang yêu cầu lấy lại hàng hoàn',  'RETURN',                29, false, true, 'Đang xử lý yêu cầu lấy lại hàng hoàn.', now(), now()),
    ('SPF-1007', 'Đã lấy hàng hoàn',                'RETURN',                30, false, true, 'Hàng hoàn đã được lấy thành công.', now(), now()),
    ('SPF-1008', 'Đã nhập kho NVC hoàn',            'RETURN',                31, false, true, 'Hàng hoàn đã được nhập kho nhà vận chuyển hoàn.', now(), now()),
    ('SPF-1009', 'Đang chuyển hoàn',                'RETURN',                32, false, true, 'Hàng đang được vận chuyển theo chiều hoàn.', now(), now()),
    ('SPF-1101', 'Đã đến kho trả trung gian',       'RETURN_DELIVERY',       33, false, true, 'Hàng hoàn đã đến kho trả trung gian.', now(), now()),
    ('SPF-1102', 'Đang trả cho NVC hoàn cuối',      'RETURN_DELIVERY',       34, false, true, 'Đang bàn giao hàng cho nhà vận chuyển thực hiện chặng hoàn cuối.', now(), now()),
    ('SPF-1103', 'Trả NVC hoàn cuối thất bại',      'RETURN_DELIVERY',       35, false, true, 'Lần bàn giao cho nhà vận chuyển hoàn cuối không thành công.', now(), now()),
    ('SPF-1104', 'Đã trả cho NVC hoàn cuối',        'RETURN_DELIVERY',       36, false, true, 'Đã bàn giao hàng cho nhà vận chuyển hoàn cuối.', now(), now()),
    ('SPF-1105', 'Đã đến kho trả cuối',             'RETURN_DELIVERY',       37, false, true, 'Hàng đã đến kho phục vụ trả cuối.', now(), now()),
    ('SPF-1106', 'Đang trả hàng',                   'RETURN_DELIVERY',       38, false, true, 'Nhà vận chuyển đang trả hàng về điểm nhận hoàn.', now(), now()),
    ('SPF-1107', 'Trả hàng thất bại',               'RETURN_DELIVERY',       39, false, true, 'Lần trả hàng không thành công.', now(), now()),
    ('SPF-1108', 'Đang yêu cầu trả lại',            'RETURN_DELIVERY',       40, false, true, 'Đang xử lý yêu cầu trả lại hàng.', now(), now()),
    ('SPF-1201', 'Đã trả hàng',                     'COMPLETED',             41, true,  true, 'Hàng đã được trả đầy đủ thành công.', now(), now()),
    ('SPF-1202', 'Đổi trả thành công',              'COMPLETED',             42, true,  true, 'Nghiệp vụ đổi trả đã hoàn tất thành công.', now(), now()),
    ('SPF-1203', 'Đã trả một phần',                 'COMPLETED',             43, true,  true, 'Nghiệp vụ trả một phần đã hoàn tất theo kết quả xác nhận.', now(), now()),
    ('SPF-0302', 'Đang tìm tài xế',                 'DRIVER_ALLOCATION',     44, false, true, 'Nhà vận chuyển tức thời đang tìm tài xế.', now(), now()),
    ('SPF-0303', 'Không tìm được tài xế',           'DRIVER_ALLOCATION',     45, false, true, 'Không còn phương án tìm tài xế tự động; cần retry, đổi phương án hoặc hủy.', now(), now())
ON CONFLICT (status_code) DO UPDATE
SET status_name = EXCLUDED.status_name,
    status_group = EXCLUDED.status_group,
    sort_no = EXCLUDED.sort_no,
    is_terminal = EXCLUDED.is_terminal,
    is_active = EXCLUDED.is_active,
    description = EXCLUDED.description,
    updated_at = now();

