export { OrdersProvider } from './components/OrdersProvider';
export { useOrders } from './model/orders-context';
export { defaultOrderInput, emptyFilters } from './model/types';
export type { Order, OrderInput, OrderFilters, OrderStatus } from './model/types';
export * from './model/spf-status-catalog';
export { validateOrder } from './model/order';
import { lazy } from 'react';
export const CreateOrderPage = lazy(() => import('./pages/CreateOrderPage'));
export const OrdersPage = lazy(() => import('./pages/OrdersPage'));
export const OrderDetailPage = lazy(() => import('./pages/OrderDetailPage'));
