export interface PrintTemplate {
  id: string;
  code: string;
  name: string;
  dimensions: string; // e.g. '4 in x 6 in'
  widthMm: number;
  heightMm: number;
  orientation: 'portrait' | 'landscape';
  printerType: string;
  description: string;
  isDefault: boolean;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export const initialPrintTemplates: PrintTemplate[] = [
  {
    id: 'tmpl-1',
    code: 'A7',
    name: 'A7 (75 mm x 100 mm)',
    dimensions: '75 mm x 100 mm',
    widthMm: 75,
    heightMm: 100,
    orientation: 'portrait',
    printerType: 'Máy in nhiệt cầm tay / Máy in mini (HPRT, Xprinter)',
    description: 'Dành cho gói hàng nhỏ, tiết kiệm giấy in nhiệt.',
    isDefault: false,
    isActive: true,
    createdAt: '2026-01-10',
    updatedAt: '2026-08-15',
  },
  {
    id: 'tmpl-2',
    code: 'A5',
    name: 'A5 (148 mm x 210 mm)',
    dimensions: '148 mm x 210 mm',
    widthMm: 148,
    heightMm: 210,
    orientation: 'portrait',
    printerType: 'Máy in văn phòng A5/A4 (Canon, HP, Brother)',
    description: 'Phiếu giao hàng khổ lớn kèm danh sách kê chi tiết hàng hóa.',
    isDefault: false,
    isActive: true,
    createdAt: '2026-01-10',
    updatedAt: '2026-08-20',
  },
  {
    id: 'tmpl-3',
    code: 'K46',
    name: 'K46 (4 in x 6 in)',
    dimensions: '4 in x 6 in (100 mm x 150 mm)',
    widthMm: 100,
    heightMm: 150,
    orientation: 'portrait',
    printerType: 'Máy in tem nhiệt chuyên dụng (Zebra, Xprinter XP-420B, Gprinter)',
    description: 'Mẫu tem chuẩn hệ thống SuperPlatform, chứa đầy đủ Barcode/QR Code và chặng NVC.',
    isDefault: true,
    isActive: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-09-01',
  },
  {
    id: 'tmpl-4',
    code: 'K50',
    name: 'K50 (50 mm x 50 mm)',
    dimensions: '50 mm x 50 mm',
    widthMm: 50,
    heightMm: 50,
    orientation: 'portrait',
    printerType: 'Máy in tem mini vuông',
    description: 'Mẫu tem nhỏ dán sản phẩm thương mại điện tử.',
    isDefault: false,
    isActive: true,
    createdAt: '2026-02-15',
    updatedAt: '2026-07-10',
  },
  {
    id: 'tmpl-5',
    code: 'K75',
    name: 'K75 (75 mm x 50 mm)',
    dimensions: '75 mm x 50 mm',
    widthMm: 75,
    heightMm: 50,
    orientation: 'landscape',
    printerType: 'Máy in tem nhiệt decal cuộn',
    description: 'Tem dán khổ ngang gọn nhẹ cho hàng tiêu dùng nhanh.',
    isDefault: false,
    isActive: true,
    createdAt: '2026-03-01',
    updatedAt: '2026-08-01',
  },
  {
    id: 'tmpl-6',
    code: 'K80',
    name: 'K80 (80 mm x 80 mm)',
    dimensions: '80 mm x 80 mm',
    widthMm: 80,
    heightMm: 80,
    orientation: 'portrait',
    printerType: 'Máy in hóa đơn bưu cục K80',
    description: 'Dùng cho bưu cục lấy/giao in bill trực tiếp tại quầy.',
    isDefault: false,
    isActive: true,
    createdAt: '2026-03-15',
    updatedAt: '2026-08-11',
  },
  {
    id: 'tmpl-7',
    code: 'SPE',
    name: 'SPE (105 mm x 35 mm)',
    dimensions: '105 mm x 35 mm',
    widthMm: 105,
    heightMm: 35,
    orientation: 'landscape',
    printerType: 'Máy in mã vạch barcode dạng dải',
    description: 'Tem dán chặng vận chuyển SuperShip Express.',
    isDefault: false,
    isActive: true,
    createdAt: '2026-04-10',
    updatedAt: '2026-07-22',
  },
  {
    id: 'tmpl-8',
    code: 'T2',
    name: 'T2 (210 mm x 280 mm)',
    dimensions: '210 mm x 280 mm',
    widthMm: 210,
    heightMm: 280,
    orientation: 'portrait',
    printerType: 'Máy in A4 tiêu chuẩn',
    description: 'Tem in nguyên trang A4 cho đơn hàng quà tặng / doanh nghiệp lớn.',
    isDefault: false,
    isActive: false,
    createdAt: '2026-05-01',
    updatedAt: '2026-06-15',
  },
  {
    id: 'tmpl-9',
    code: 'S8',
    name: 'S8 (9 cm x 6 cm)',
    dimensions: '9 cm x 6 cm',
    widthMm: 90,
    heightMm: 60,
    orientation: 'landscape',
    printerType: 'Máy in decal cuộn S-Series',
    description: 'Tem dán túi niêm phong màng co.',
    isDefault: false,
    isActive: true,
    createdAt: '2026-06-01',
    updatedAt: '2026-08-30',
  },
  {
    id: 'tmpl-10',
    code: 'S9',
    name: 'S9 (9 cm x 6 cm)',
    dimensions: '9 cm x 6 cm',
    widthMm: 90,
    heightMm: 60,
    orientation: 'landscape',
    printerType: 'Máy in decal cuộn S-Series',
    description: 'Mẫu tem mở rộng dán nhãn phân loại NVC.',
    isDefault: false,
    isActive: true,
    createdAt: '2026-06-10',
    updatedAt: '2026-09-02',
  },
];
